---

- name: Create a directory if it does not exist
  file:
    path: /home/ubuntu/deployapp1
    state: directory
    mode: '0755'
 
- name: Changing the Directory
  command: cd deployapp1

- name: Cloning Git Repository
  git:
     repo: https://ansible-story@dev.azure.com/ansible-story/springbootapp_mumbai/_git/springbootapp_mumbai
     dest: /home/ubuntu/deployapp1
     version: master

- name: Changing to source Code Repo
  command: cd  /home/ubuntu/deployapp1/springbootapp_mumbai/FlightStatusServiceImpl/

- name: Maven clean and Package
  command: mvn clean package

- name: Copying the jar file to tomcat server.
  command: cp  /home/ubuntu/deployapp1/springbootapp_mumbai/FlightStatusServiceImpl/target/FlightStatusServiceImpl-0.1.0.jar /usr/share/tomcat/webapps/
 
- name: maven run the app server
  command:  mvn spring-boot:run -Doracle.jdbc.timezoneAsRegion=false

